const canvas=document.querySelector('#fog'),ctx=canvas.getContext('2d');
const palettes=[{name:'Dusk',colors:[[99,124,205],[167,113,207],[223,139,178]]},{name:'Aurora',colors:[[61,123,181],[77,178,165],[170,209,153]]},{name:'Ember',colors:[[134,64,124],[214,114,102],[233,176,110]]},{name:'Silver',colors:[[99,121,149],[164,176,193],[212,206,216]]}];
let width,height,cols,rows,time=0,last=0,palette=0,speed=.5,density=.55,paused=matchMedia('(prefers-reduced-motion: reduce)').matches;
const pointer={x:-1000,y:-1000},chars=' .,:;-=+*#%@',cellX=9,cellY=13;
function resize(){width=innerWidth;height=innerHeight;const dpr=Math.min(devicePixelRatio||1,2);canvas.width=width*dpr;canvas.height=height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);cols=Math.ceil(width/cellX);rows=Math.ceil(height/cellY);ctx.font='10px monospace';draw()}
function hash(x,y){let n=Math.sin(x*127.1+y*311.7)*43758.5453;return n-Math.floor(n)}
function noise(x,y){const ix=Math.floor(x),iy=Math.floor(y);let fx=x-ix,fy=y-iy;fx=fx*fx*(3-2*fx);fy=fy*fy*(3-2*fy);return (hash(ix,iy)*(1-fx)+hash(ix+1,iy)*fx)*(1-fy)+(hash(ix,iy+1)*(1-fx)+hash(ix+1,iy+1)*fx)*fy}
function draw(){ctx.clearRect(0,0,width,height);const colors=palettes[palette].colors;for(let y=0;y<rows;y++){for(let x=0;x<cols;x++){const px=x*cellX,py=y*cellY,nx=px/width,ny=py/height;const warp=noise(x*.019+time*.045,y*.025-time*.03);let n=noise(x*.036+warp*2.8+time*.13,y*.048+warp*2-time*.11)*.64+noise(x*.077-time*.15,y*.096+time*.08)*.26+noise(x*.18+time*.04,y*.2)*.1;const ribbon=Math.exp(-Math.pow((ny-(.56+Math.sin(nx*5+time*.08)*.16))/.29,2));const focal=.42+.58*Math.min(1,nx*1.6);const dist=Math.hypot(px-pointer.x,py-pointer.y);n+=Math.exp(-dist*dist/16000)*.1;let strength=Math.max(0,(n-.29+(density-.55)*.22)*2)*ribbon*focal;strength=Math.min(1,strength);if(strength<.035)continue;const character=chars[Math.min(chars.length-1,Math.floor(strength*12))];if(character===' ')continue;const mix=Math.max(0,Math.min(1,nx*.7+ny*.24+noise(x*.018+time*.03,y*.025)*.55-.2))*2;const a=colors[Math.min(1,Math.floor(mix))],b=colors[Math.min(2,Math.floor(mix)+1)],f=mix%1;ctx.fillStyle=`rgba(${Math.round(a[0]+(b[0]-a[0])*f)},${Math.round(a[1]+(b[1]-a[1])*f)},${Math.round(a[2]+(b[2]-a[2])*f)},${Math.min(.92,strength*1.35)})`;ctx.fillText(character,px,py)}}}
function frame(now){const dt=Math.min((now-last)/1000,.05);if(now-last>40){if(!paused){time+=dt*speed;draw()}last=now}requestAnimationFrame(frame)}
function updatePause(){document.querySelector('#pause-icon').textContent=paused?'▷':'Ⅱ';document.querySelector('#pause').setAttribute('aria-label',paused?'Resume animation':'Pause animation');document.querySelector('#play-status').textContent=paused?'Resume motion':'Pause motion';document.querySelector('#render-status').textContent=paused?'A moment of stillness':'Rendering in real time'}
document.querySelector('#pause').addEventListener('click',()=>{paused=!paused;updatePause()});
document.querySelectorAll('.swatch').forEach(button=>button.addEventListener('click',()=>{palette=Number(button.dataset.palette);document.querySelectorAll('.swatch').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button))});document.querySelector('#palette-name').textContent=palettes[palette].name;draw()}));
document.querySelector('#speed').addEventListener('input',e=>{speed=Number(e.target.value);document.querySelector('#speed-value').textContent=speed.toFixed(1)+'×';e.target.style.setProperty('--fill',speed/1.5*100+'%')});
document.querySelector('#density').addEventListener('input',e=>{density=Number(e.target.value)/100;document.querySelector('#density-value').textContent=density<.34?'Light':density>.7?'Heavy':'Medium';e.target.style.setProperty('--fill',density*100+'%');draw()});
window.addEventListener('pointermove',e=>{pointer.x=e.clientX;pointer.y=e.clientY});document.addEventListener('pointerleave',()=>{pointer.x=-1000;pointer.y=-1000});window.addEventListener('resize',resize);
const dialog=document.querySelector('#about-dialog');document.querySelector('#about').addEventListener('click',()=>dialog.showModal());document.querySelector('#close-about').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
updatePause();resize();requestAnimationFrame(frame);
